name: Deploy to ECS using Terraform and CodeDeploy

on:
  workflow_dispatch:  # Triggered manually via the GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7 

      # Step 3: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 4: Terraform Init
      - name: Terraform Init
        run: |
          cd terraform2
          terraform init

      # Step 5: Terraform Plan
      - name: Terraform Plan
        run: |
          cd terraform2
          terraform plan

      # Step 6: Terraform Apply
      - name: Terraform Apply
        run: |
          cd terraform2
          terraform apply -auto-approve

      # Step 7: Get ECS Task Definition ARN
      - name: Get ECS Task Definition ARN
        id: get_task_def
        run: |
          TASK_ARN=$(aws ecs list-task-definitions \
            --family-prefix tyagi-task \
            --sort DESC \
            --max-items 1 \
            --query 'taskDefinitionArns[0]' \
            --output text)
          echo "taskDefinitionArn=$TASK_ARN" >> $GITHUB_OUTPUT

      # Step 8: Trigger CodeDeploy Deployment
      - name: Trigger CodeDeploy Deployment
        run: |
          aws deploy create-deployment \
            --application-name tyagi-codedeploy-app \
            --deployment-group-name tyagi-deployment-group \
            --deployment-config-name CodeDeployDefault.ECSCanary10Percent5Minutes \
            --revision revisionType=AppSpecContent,appSpecContent="{\"version\":\"1.0\",\"Resources\":[{\"TargetService\":{\"Type\":\"AWS::ECS::Service\",\"Properties\":{\"TaskDefinition\":\"${{ steps.get_task_def.outputs.taskDefinitionArn }}\",\"LoadBalancerInfo\":{\"ContainerName\":\"strapi\",\"ContainerPort\":80}}}}]}"
