name: Deploy with Terraform

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker Image Tag to deploy (e.g. 1713453456)'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials from secrets
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "[default]" > ~/.aws/config
          echo "region=${{ secrets.AWS_REGION }}" >> ~/.aws/config

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform
        env:
          TF_VAR_image_tag: ${{ github.event.inputs.image_tag }}
          TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
        run: terraform plan

      - name: Terraform Apply
        working-directory: ./terraform
        env:
          TF_VAR_image_tag: ${{ github.event.inputs.image_tag }}
          TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
        run: terraform apply -auto-approve
