name: Terraform Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: |
          terraform apply -auto-approve \
            -var="aws_region=us-east-1" \
            -var="ami_id=ami-xxxxxxxxxxxx" \
            -var="instance_type=t3.micro" \
            -var="subnet_id=subnet-xxxxxxxx" \
            -var="security_group_id=sg-xxxxxxxx" \
            -var="instance_profile=ec2-role" \
            -var="ecr_repository_url=118273046134.dkr.ecr.us-east-1.amazonaws.com/vishal-strapi-app" \
            -var="image_tag=${{ github.sha }}" \
            -var="ecr_registry=118273046134.dkr.ecr.us-east-1.amazonaws.com"
